version: '3'
services:
  authors:
    image: lohika/bff-authors-service:1.0
    container_name: bff-authors-service
    networks:
      - mynet
  books:
    image: lohika/bff-books-service:1.0
    container_name: bff-books-service
    networks:
      - mynet
  web-sockets:
    image: lohika/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    networks:
      - mynet
#  mobile-app:
#    image: lohika/bff-mobile-app:1.0
#    container_name: bff-mobile-app
#    networks:
#      - mynet
#  client-app:
#    image: lohika/bff-client-app:1.0
#    container_name: bff-client-app
#    networks:
#      - mynet
  frontend:
    image: lohika/bff-frontend:1.0
    container_name: bff-frontend
    networks:
      - mynet
  mobile-frontend:
    image: lohika/bff-mobile-frontend:1.0
    container_name: bff-mobile-frontend
    networks:
      - mynet
  gateway:
    image: lohika/bff-gateway:1.0
    container_name: bff-gateway
    ports:
      - 8080:8080
    networks:
      - mynet
  mobile-gateway:
    image: lohika/bff-mobile-gateway:1.0
    container_name: bff-mobile-gateway
    ports:
      - 8081:8080
    networks:
      - mynet
  redis:
    image: redis:latest
    container_name: bff-redis
    ports:
      - 16379:6379
    networks:
      - mynet
networks:
  mynet:
